- GDay/src/main/java/team/project/gday/HomeController.java
- GDay/src/main/java/team/project/gday/payment/controller/PaymentController.java
- GDay/src/main/webapp/WEB-INF/views/common/header.jsp
- GDay/src/main/webapp/WEB-INF/views/common/main.jsp
- GDay/src/main/webapp/WEB-INF/views/home.jsp
- GDay/src/main/webapp/WEB-INF/views/payment/order.jsp
- GDay/src/main/webapp/WEB-INF/views/payment/refund.jsp
- GDay/src/main/webapp/resources/css/header.css
header/main JSP 수정
payment Controller 추가
payment JSP 추가
> homeController

- GDay/src/main/java/team/project/gday/member/gmem/controller/GmemController.java
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemOrderList1.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemSidebar.jsp
- GDay/src/main/webapp/resources/css/mypage/listPeriod.css
- GDay/src/main/webapp/resources/css/mypage/mypageList.css
- GDay/src/main/webapp/resources/js/mypage/listPeriod.js
헤더 -> 컨트롤러 연결
css 폴더
js 폴더
css, js, jsp 파일 추가
> 일반회원 마이페이지 주문내역(선물리스트)

- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemOrderList1.jsp
- GDay/src/main/webapp/resources/css/common/reset.css
reset.css(영주 코드) + gMemOrderList1.jsp 헤더 추가
> reset.css(영주 코드) + gMemOrderList1.jsp 헤더 추가

- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemOrderList1.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemSidebar.jsp
- GDay/src/main/webapp/resources/css/mypage/gmemSidebar.css
- GDay/src/main/webapp/resources/css/mypage/listPeriod.css
- GDay/src/main/webapp/resources/css/mypage/mypageList.css
> 일반 회원 마이페이지 선물리스트

- GDay/src/main/java/team/project/gday/search/gClass/controller/GclassController.java
- GDay/src/main/java/team/project/gday/search/gift/controller/GiftController.java
- GDay/src/main/webapp/WEB-INF/views/common/bMain.jsp
- GDay/src/main/webapp/WEB-INF/views/gClass/gClassView.jsp
- GDay/src/main/webapp/resources/css/common/bMain.css
> 비즈니스 메인 일부 수정 + 기프트 클래스 틀 잡음

- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemOrderList1.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemSidebar.jsp
- GDay/src/main/webapp/resources/css/mypage/gmemSidebar.css
- GDay/src/main/webapp/resources/css/mypage/listPeriod.css
- GDay/src/main/webapp/resources/css/mypage/mypageList.css
마이페이지 (일반) -선물 리스트 프론트 
-마이페이지(일반) 사이드바 (반응형까지 완 + 코드 몇개 수정)
-선물 리스트 (반응형 50%)
> 마이페이지 (일반) -선물 리스트 프론트 

- GDay/src/main/java/team/project/gday/member/gmem/controller/GmemController.java
- GDay/src/main/webapp/WEB-INF/views/mypage/bMemPage/bMemSidebar.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/bMemPage/bMemUpdate.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemOrderList1.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemUpdate.jsp
- GDay/src/main/webapp/resources/css/mypage/bMemInfoUpdate.css
- GDay/src/main/webapp/resources/css/mypage/gMemInfoUpdate.css
- GDay/src/main/webapp/resources/css/mypage/gmemSidebar.css
- GDay/src/main/webapp/resources/css/mypage/listPeriod.css
- GDay/src/main/webapp/resources/css/mypage/mypageList.css
- GDay/src/main/webapp/resources/js/mypage/bMemInfoUpdate.js
- GDay/src/main/webapp/resources/js/mypage/gMemInfoUpdate.js
일반회원/비즈니스회원 내정보 수정 페이지 반응형까지 완료 + 프로필 모달창
일반회원 주문 조회 반응형 완료
> 일반회원/비즈니스회원 내정보 수정 페이지 + 일반회원 주문조회 반응형

- GDay/src/main/java/team/project/gday/member/gmem/controller/GmemController.java
- GDay/src/main/webapp/WEB-INF/views/mypage/bMemPage/bMemUpdate.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemOrderList1.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemSidebar.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemUpdate.jsp
- GDay/src/main/webapp/resources/css/mypage/gMemInfoUpdate.css
- GDay/src/main/webapp/resources/css/mypage/gmemSidebar.css
일반회원 / 비즈니스 회원 전화번호필수표시 없앰 + 사이드바 헤더 햄버거 위치 변경
> 일반회원 / 비즈니스 회원 전화번호필수표시 없앰 + 사이드바 헤더 햄버거 위치 변경

- GDay/src/main/java/team/project/gday/member/gmem/controller/GmemCartController.java
- GDay/src/main/webapp/WEB-INF/views/common/header.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemCart.jsp
- GDay/src/main/webapp/WEB-INF/views/payment/order.jsp
- GDay/src/main/webapp/resources/css/common/header.css
- GDay/src/main/webapp/resources/css/mypage/memberCart.css
- GDay/src/main/webapp/resources/css/payment/order.css
header jsp,css 수정
장바구니 컨트롤러 추가
> 일반회원 장바구니 jsp, css 수정

- GDay/src/main/java/team/project/gday/member/bmem/controller/BmemController.java
- GDay/src/main/webapp/WEB-INF/views/common/main.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/bMemPage/bMemSidebar.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/bMemPage/bMemUpdate.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/bMemPage/bOrderList.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/bMemPage/bSellList.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemCart.jsp
- GDay/src/main/webapp/WEB-INF/views/payment/order.jsp
- GDay/src/main/webapp/resources/css/payment/order.css
> main jsp 지워진거 추가

- GDay/src/main/java/team/project/gday/calendar/CalendarController.java
- GDay/src/main/webapp/WEB-INF/views/calendar/calendar.jsp
- GDay/src/main/webapp/WEB-INF/views/calendar/calendarJS.jsp
- GDay/src/main/webapp/resources/css/calendar.css
- GDay/src/main/webapp/resources/fullcalendar/css/main.css
- GDay/src/main/webapp/resources/fullcalendar/js/locales-all.js
- GDay/src/main/webapp/resources/fullcalendar/js/main.js
> 캘린더 jsp, 컨트롤러 및 resources 추가

- GDay/src/main/java/team/project/gday/calendar/CalendarController.java
- GDay/src/main/java/team/project/gday/calendar/model/dao/CalendarDAO.java
- GDay/src/main/java/team/project/gday/calendar/model/service/CalendarService.java
- GDay/src/main/java/team/project/gday/calendar/model/service/CalendarServiceImpl.java
- GDay/src/main/java/team/project/gday/calendar/model/vo/Calendar.java
- GDay/src/main/resources/mappers/calendar-mapper.xml
- GDay/src/main/resources/mybatis-config.xml
- GDay/src/main/webapp/WEB-INF/views/calendar/calendar.jsp
- GDay/src/main/webapp/WEB-INF/views/calendar/calendarJS.jsp
> 캘린더 전체 기념일 조회 끝

- GDay/src/main/java/team/project/gday/member/bmem/controller/BmemController.java
- GDay/src/main/webapp/WEB-INF/views/mypage/bMemPage/bCancelList.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/bMemPage/bMemSidebar.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/bMemPage/bOrderList.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/bMemPage/bRefundList.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/bMemPage/bSellList.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemCart.jsp
- GDay/src/main/webapp/WEB-INF/views/payment/order.jsp
- GDay/src/main/webapp/resources/css/mypage/bMemPage/bCancelList.css
- GDay/src/main/webapp/resources/css/mypage/bMemPage/bOrderList.css
- GDay/src/main/webapp/resources/css/mypage/bMemPage/bRefundList.css
- GDay/src/main/webapp/resources/css/mypage/bMemPage/bSellList.css
- GDay/src/main/webapp/resources/css/mypage/memberCart.css
> 비즈니스 회원 마이페이지 jsp/css

- GDay/src/main/java/team/project/gday/admin/controller/AdminController.java
- GDay/src/main/java/team/project/gday/admin/model/service/AdminService.java
- GDay/src/main/java/team/project/gday/admin/model/service/AdminServiceImpl.java
- GDay/src/main/webapp/WEB-INF/views/admin/adminBlackMem.jsp
- GDay/src/main/webapp/WEB-INF/views/admin/adminMember.jsp
- GDay/src/main/webapp/WEB-INF/views/admin/memberCustomer.jsp
- GDay/src/main/webapp/WEB-INF/views/admin/memberCustomerInsert.jsp
> memberCustomer파일 → 챗봇 연동

- GDay/src/main/java/team/project/gday/calendar/CalendarController.java
- GDay/src/main/java/team/project/gday/calendar/model/dao/CalendarDAO.java
- GDay/src/main/java/team/project/gday/calendar/model/service/CalendarService.java
- GDay/src/main/java/team/project/gday/calendar/model/service/CalendarServiceImpl.java
- GDay/src/main/java/team/project/gday/calendar/model/vo/Calendar.java
- GDay/src/main/resources/mappers/calendar-mapper.xml
- GDay/src/main/webapp/WEB-INF/views/calendar/calendar.jsp
- GDay/src/main/webapp/WEB-INF/views/calendar/calendarJS.jsp
- GDay/src/main/webapp/resources/css/calendar.css
> 마이캘린더 1차 끝

- GDay/src/main/webapp/WEB-INF/views/common/main.jsp
> 메인페이지 임시 마이페이지 a 링크 변경

- GDay/src/main/java/team/project/gday/Product/model/vo/Order.java
- GDay/src/main/resources/mappers/mypage/gmem/gmem-mapper.xml
- GDay/src/main/resources/mybatis-config.xml
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemSidebar.jsp
- GDay/src/main/webapp/resources/css/mypage/gmemSidebar.css
gmem 매퍼 + order Vo 추가
mybatis 매퍼 연결 + 별칭 추가
일반회원 사이드바 수정(사이드바 위치 고정)
> gmem 매퍼 + order Vo + mybatis + sidebar 수정

- GDay/src/main/java/team/project/gday/member/gmem/controller/GmemController.java
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemOrderList2.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemOrderListJS1.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemOrderListJS2.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemOrderView1.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemOrderView2.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemOrderViewJS1.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/orderListTab.jsp
- GDay/src/main/webapp/resources/css/mypage/gmemOrderView.css
- GDay/src/main/webapp/resources/css/mypage/mypageList.css
> 일반회원 마이페이지 추가 / 수정

- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemOrderView2.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemSidebar.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemUpdate.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemUpdateJS.jsp
- GDay/src/main/webapp/resources/css/mypage/gMemInfoUpdate.css
- GDay/src/main/webapp/resources/css/mypage/gmemOrderView.css
> 일반회원 상세조회 추가 + 내정보수정 수정

- GDay/src/main/webapp/WEB-INF/views/mypage/bMemPage/bMemUpdate.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemSidebar.jsp
- GDay/src/main/webapp/resources/css/mypage/bMemInfoUpdate.css
- GDay/src/main/webapp/resources/js/mypage/bMemInfoUpdate.js
비즈니스 멤버 내정보수정 프로필 모달창 수정 + 일반회원 사이드바 경로 수정
> 비즈니스 멤버 내정보수정 프로필 모달창 수정 + 일반회원 사이드바 경로 수정

- GDay/src/main/java/team/project/gday/member/gmem/controller/GmemController.java
- GDay/src/main/webapp/WEB-INF/views/calendar/calendar.jsp
- GDay/src/main/webapp/WEB-INF/views/calendar/calendarJS.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemCancelReqst1.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemCancelReqst2.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemOrderList1.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemOrderView1.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemOrderView2.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemReviewList.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemSidebar.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemWishList.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/orderListTab.jsp
- GDay/src/main/webapp/WEB-INF/views/review/reviewInsertForm.jsp
- GDay/src/main/webapp/resources/css/calendar/calendar.css
- GDay/src/main/webapp/resources/css/common/modalBasic.css
- GDay/src/main/webapp/resources/css/mypage/gmemOrderView.css
- GDay/src/main/webapp/resources/css/mypage/mypageList.css
- GDay/src/main/webapp/resources/css/mypage/requestCancel.css
- GDay/src/main/webapp/resources/css/mypage/reviewList.css
- GDay/src/main/webapp/resources/css/mypage/wishList.css
- GDay/src/main/webapp/resources/css/review/reviewInsert.css
-리뷰 관련 폴더 생성
-마이페이지 리뷰, 위시리스트, 취소 요청 추가
> 일반회원 마이페이지 프론트 추가 + 후기 삽입 페이지(모달)추가

- GDay/src/main/java/team/project/gday/Product/model/vo/Order.java
- GDay/src/main/resources/mappers/mypage/gmem/gmem-mapper.xml
ORDER VO 수정(필드 추가) + DB V_ORDER 컬럼 수정 + gmem-매퍼 수정
> ORDER VO 수정(필드 추가) + DB V_ORDER 컬럼 수정 + gmem-매퍼 수정

- GDay/src/main/java/team/project/gday/Product/model/vo/Order.java
- GDay/src/main/resources/mappers/mypage/gmem/gmem-mapper.xml
ORDER VO + GMEM MAPPER 재수정...O_O;;;;;
> ORDER VO + GMEM MAPPER 재수정...O_O;;;;;

- GDay/src/main/webapp/WEB-INF/views/admin/adminBMemSub.jsp
- GDay/src/main/webapp/WEB-INF/views/admin/adminBMemView.jsp
- GDay/src/main/webapp/WEB-INF/views/admin/adminBlackMem.jsp
- GDay/src/main/webapp/WEB-INF/views/admin/adminBoard.jsp
- GDay/src/main/webapp/WEB-INF/views/admin/adminCustomerService.jsp
- GDay/src/main/webapp/WEB-INF/views/admin/adminMember.jsp
- GDay/src/main/webapp/WEB-INF/views/admin/adminReply.jsp
- GDay/src/main/webapp/WEB-INF/views/admin/adminReportEnd.jsp
- GDay/src/main/webapp/WEB-INF/views/admin/adminReportStand.jsp
- GDay/src/main/webapp/WEB-INF/views/admin/adminSidebar.jsp
- GDay/src/main/webapp/WEB-INF/views/admin/memberCustomer.jsp
- GDay/src/main/webapp/WEB-INF/views/admin/memberCustomerInsert.jsp
- GDay/src/main/webapp/WEB-INF/views/admin/memberCustomerView.jsp
- GDay/src/main/webapp/resources/css/admin/adminPage.css
- GDay/src/main/webapp/resources/css/admin/adminSidebar.css
챗봇: 원하는 답변 없을 시 1:1문의 페이지 삽입
관리자 CSS 추가
> 관리자 페이지 정리(페이징바 X)

- GDay/src/main/java/team/project/gday/Product/model/vo/Order.java
- GDay/src/main/java/team/project/gday/calendar/CalendarController.java
- GDay/src/main/java/team/project/gday/member/gmem/controller/GmemController.java
- GDay/src/main/java/team/project/gday/member/gmem/model/dao/GmemDAO.java
- GDay/src/main/java/team/project/gday/member/gmem/model/service/GmemService.java
- GDay/src/main/java/team/project/gday/member/gmem/model/service/GmemServiceImpl.java
- GDay/src/main/java/team/project/gday/review/model/vo/Review.java
- GDay/src/main/resources/mappers/mypage/gmem/gmem-mapper.xml
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemCancelReqstC.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemCancelReqstG.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemCancelViewG.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemOrderListC.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemOrderListG.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemOrderListJSC.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemOrderListJSG.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemOrderViewC.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemReviewList.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemSidebar.jsp
- GDay/src/main/webapp/WEB-INF/views/review/reviewInsertForm.jsp
- GDay/src/main/webapp/resources/css/mypage/gmemOrderView.css
- GDay/src/main/webapp/resources/css/mypage/gmemSidebar.css
- GDay/src/main/webapp/resources/css/mypage/mypageList.css
> 마이페이지 일반 jsp 파일명 및 경로 변경

- GDay/src/main/java/team/project/gday/member/gmem/controller/GmemController.java
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemOrderListC.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemOrderListG.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemOrderListJSC.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemOrderListJSG.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemOrderViewC.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemOrderViewG.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/orderListTab.jsp
- GDay/src/main/webapp/WEB-INF/views/review/reviewInsertForm.jsp
- GDay/src/main/webapp/resources/css/mypage/gmemOrderView.css
- GDay/src/main/webapp/resources/css/mypage/mypageList.css
> 주문 조회 클래스 부분

- GDay/src/main/java/team/project/gday/Product/model/vo/Order.java
- GDay/src/main/java/team/project/gday/member/gmem/controller/GmemController.java
- GDay/src/main/java/team/project/gday/member/gmem/model/dao/GmemDAO.java
- GDay/src/main/java/team/project/gday/member/gmem/model/service/GmemService.java
- GDay/src/main/java/team/project/gday/member/gmem/model/service/GmemServiceImpl.java
- GDay/src/main/java/team/project/gday/review/model/vo/Review.java
- GDay/src/main/resources/mappers/mypage/gmem/gmem-mapper.xml
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemOrderListJSG.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemOrderViewG.jsp
> 주문 상세 중간까지 했음

- GDay/src/main/webapp/WEB-INF/views/common/header.jsp
> header : swal 스크립트 추가

- GDay/src/main/java/team/project/gday/member/gmem/controller/GmemController.java
- GDay/src/main/java/team/project/gday/member/gmem/model/service/GmemServiceImpl.java
- GDay/src/main/resources/mappers/mypage/gmem/gmem-mapper.xml
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemOrderListG.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemOrderListJSC.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemOrderListJSG.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemOrderViewC.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemOrderViewG.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemOrderViewJS.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemSidebar.jsp
- GDay/src/main/webapp/WEB-INF/views/review/reviewInsertForm.jsp
- GDay/src/main/webapp/resources/css/mypage/gmemOrderView.css
- GDay/src/main/webapp/resources/css/mypage/mypageList.css
> 클래스/선물 주문 상세 조회 1차 완료

- GDay/src/main/java/team/project/gday/member/model/vo/Refund.java
- GDay/src/main/resources/mybatis-config.xml
member/model/vo/Refund VO 추가 + mybatis.xml 별칭 추가
> member/model/vo/Refund VO 추가 + mybatis.xml 별칭 추가

- GDay/src/main/java/team/project/gday/member/gmem/controller/GmemController.java
- GDay/src/main/java/team/project/gday/member/gmem/model/dao/GmemDAO.java
- GDay/src/main/java/team/project/gday/member/gmem/model/service/GmemService.java
- GDay/src/main/java/team/project/gday/member/gmem/model/service/GmemServiceImpl.java
- GDay/src/main/java/team/project/gday/member/model/vo/ListCondition.java
- GDay/src/main/resources/mappers/mypage/gmem/gmem-mapper.xml
- GDay/src/main/webapp/WEB-INF/views/calendar/calendar.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemCancelReqstC.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemCancelReqstG.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemCancelViewG.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemOrderListC.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemOrderListG.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemOrderListJSC.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemOrderListJSG.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemOrderViewC.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemOrderViewG.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemOrderViewJS.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemReviewList.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemSidebar.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemUpdate.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemWishList.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/orderListTab.jsp
- GDay/src/main/webapp/resources/css/calendar/calendar.css
- GDay/src/main/webapp/resources/css/common/modalBasic.css
- GDay/src/main/webapp/resources/css/mypage/gmemOrderView.css
- GDay/src/main/webapp/resources/css/mypage/gmemSidebar.css
- GDay/src/main/webapp/resources/css/mypage/listPeriod.css
- GDay/src/main/webapp/resources/css/mypage/mypageList.css
- GDay/src/main/webapp/resources/css/mypage/requestCancel.css
- GDay/src/main/webapp/resources/js/mypage/listPeriod.js
주문 취소/반품 요청 및 listCondition VO 생성
> 주문 취소/반품 요청 및 listCondition VO 생성

- GDay/src/main/resources/spring/appServlet/servlet-context.xml
> 스케줄링을 기본 세팅을 위한 서블릿 추가

- GDay/src/main/java/team/project/gday/admin/controller/AdminController.java
- GDay/src/main/java/team/project/gday/admin/model/dao/AdminDAO.java
- GDay/src/main/java/team/project/gday/admin/model/service/AdminService.java
- GDay/src/main/java/team/project/gday/admin/model/service/AdminServiceImpl.java
- GDay/src/main/java/team/project/gday/admin/model/vo/Customor.java
- GDay/src/main/resources/mappers/admin-mapper.xml
- GDay/src/main/resources/mybatis-config.xml
- GDay/src/main/webapp/WEB-INF/views/admin/adminBlackMem.jsp
- GDay/src/main/webapp/WEB-INF/views/admin/adminBoard.jsp
- GDay/src/main/webapp/WEB-INF/views/admin/adminCustomerService.jsp
- GDay/src/main/webapp/WEB-INF/views/admin/adminMagazine.jsp
- GDay/src/main/webapp/WEB-INF/views/admin/adminMember.jsp
- GDay/src/main/webapp/resources/css/admin/adminPage.css
전체회원, 블랙리스트 회원, 게시글 조회, 매거진 조회 기능
관리자 고객센터 리스트 조회 중
> 페이징 바 css 적용

- GDay/src/main/java/team/project/gday/member/gmem/controller/GmemController.java
- GDay/src/main/java/team/project/gday/member/gmem/model/dao/GmemDAO.java
- GDay/src/main/java/team/project/gday/member/gmem/model/service/GmemService.java
- GDay/src/main/java/team/project/gday/member/gmem/model/service/GmemServiceImpl.java
- GDay/src/main/java/team/project/gday/member/model/vo/ListCondition.java
- GDay/src/main/resources/mappers/mypage/gmem/gmem-mapper.xml
- GDay/src/main/webapp/WEB-INF/views/calendar/calendarJS.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemCancelReqstC.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemCancelReqstG.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemOrderListC.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemOrderListG.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemOrderListJSC.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemOrderListJSG.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemOrderViewC.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemOrderViewG.jsp
- GDay/src/main/webapp/resources/css/mypage/mypageList.css
orderList css 수정
orderCancelView용 returnViewURL 세션 등록 등
orderList mapper sql 수정
> orderList mapper sql 오류 수정 등

- GDay/src/main/java/team/project/gday/gClass/model/service/GClassServiceImpl.java
> 썸머노트 수정 버그픽스 (썸네일이 같이 사라지는 현상)

- GDay/src/main/webapp/WEB-INF/views/admin/reportForm.jsp
- GDay/src/main/webapp/WEB-INF/views/gClass/gClassView.jsp
> 신고하기 클릭 시 팝업창 뜨기

- GDay/src/main/java/team/project/gday/member/gmem/controller/GmemController.java
- GDay/src/main/java/team/project/gday/member/gmem/model/dao/GmemDAO.java
- GDay/src/main/java/team/project/gday/member/gmem/model/service/GmemService.java
- GDay/src/main/java/team/project/gday/member/gmem/model/service/GmemServiceImpl.java
- GDay/src/main/resources/mappers/mypage/gmem/gmem-mapper.xml
- GDay/src/main/webapp/WEB-INF/views/calendar/calendar.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemCancelReqstG.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemCancelViewC.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemCancelViewG.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemOrderListJSC.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemOrderViewC.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemOrderViewG.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemOrderViewJS.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/orderListTab.jsp
- GDay/src/main/webapp/WEB-INF/views/review/reviewInsertForm.jsp
- GDay/src/main/webapp/resources/css/mypage/gmemOrderView.css
- GDay/src/main/webapp/resources/css/mypage/mypageList.css
주문 취소 상세 뷰 연결 오류 + 주문 조회 버튼 추가 + 캘린더 푸터 추가 등
> 주문 취소 상세 뷰 연결 오류 + 주문 조회 버튼 추가 + 캘린더 푸터 추가 등

- GDay/src/main/java/team/project/gday/review/controller/ReviewController.java
- GDay/src/main/java/team/project/gday/review/model/dao/ReviewDAO.java
- GDay/src/main/java/team/project/gday/review/model/service/ReviewService.java
- GDay/src/main/java/team/project/gday/review/model/service/ReviewServiceImpl.java
- GDay/src/main/resources/mappers/review-mapper.xml
- GDay/src/main/resources/mybatis-config.xml
> 리뷰 매퍼 + mvc 세팅

- GDay/src/main/java/team/project/gday/review/model/dao/ReviewDAO.java
> reviewDAO 어노테이션추가

- GDay/src/main/java/team/project/gday/admin/controller/AdminController.java
- GDay/src/main/java/team/project/gday/admin/model/dao/AdminDAO.java
- GDay/src/main/java/team/project/gday/admin/model/service/AdminService.java
- GDay/src/main/java/team/project/gday/admin/model/service/AdminServiceImpl.java
- GDay/src/main/resources/mappers/admin-mapper.xml
- GDay/src/main/webapp/WEB-INF/views/admin/adminBMemSub.jsp
- GDay/src/main/webapp/WEB-INF/views/admin/adminBMemView.jsp
- GDay/src/main/webapp/WEB-INF/views/admin/adminBoard.jsp
- GDay/src/main/webapp/WEB-INF/views/admin/adminCustomerService.jsp
- GDay/src/main/webapp/WEB-INF/views/admin/adminReply.jsp
- GDay/src/main/webapp/WEB-INF/views/admin/adminReportEnd.jsp
- GDay/src/main/webapp/WEB-INF/views/admin/adminReportStand.jsp
- GDay/src/main/webapp/WEB-INF/views/admin/memberCustomer.jsp
- GDay/src/main/webapp/WEB-INF/views/admin/memberCustomerView.jsp
- GDay/src/main/webapp/WEB-INF/views/admin/reportForm.jsp
- GDay/src/main/webapp/WEB-INF/views/gift/giftView.jsp
> 회원 고객센터 목록 조회 작업중

- GDay/src/main/java/team/project/gday/review/model/vo/Review.java
> review VO 수정

- GDay/src/main/webapp/WEB-INF/views/mypage/accountDelete.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/bMemPage/bMemSidebar.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemSidebar.jsp
사이드바 이미지 기본 이미지 설정 추가 + 탈퇴 페이지 사이드바 비율 적용
> 사이드바 이미지 기본 이미지 설정 추가 + 탈퇴 페이지 사이드바 비율 적용

- GDay/src/main/java/team/project/gday/common/scheduling/SendSMSbyN.java
- GDay/src/main/java/team/project/gday/member/bmem/controller/BmemController.java
- GDay/src/main/java/team/project/gday/member/gmem/controller/GmemController.java
- GDay/src/main/java/team/project/gday/member/gmem/model/dao/GmemDAO.java
- GDay/src/main/java/team/project/gday/member/gmem/model/service/GmemService.java
- GDay/src/main/java/team/project/gday/member/gmem/model/service/GmemServiceImpl.java
- GDay/src/main/resources/mappers/mypage/gmem/gmem-mapper.xml
- GDay/src/main/webapp/WEB-INF/views/admin/adminSidebar.jsp
- GDay/src/main/webapp/WEB-INF/views/calendar/calendarJS.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/accountDelete.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/bMemPage/bMemSidebar.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemSidebar.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/memPwdUpdate.jsp
- GDay/src/main/webapp/resources/css/admin/adminSidebar.css
- GDay/src/main/webapp/resources/css/mypage/gmemSidebar.css
- GDay/src/main/webapp/resources/css/mypage/memPwdUpdate.css
> 비번 변경 기능 + css 수정

- GDay/src/main/webapp/WEB-INF/views/review/reviewView.jsp
reviewView.jsp - 상세 페이지 후기 리스트 jsp
> reviewView.jsp - 상세 페이지 후기 리스트 jsp

- GDay/src/main/java/team/project/gday/review/controller/ReviewController.java
- GDay/src/main/java/team/project/gday/review/model/dao/ReviewDAO.java
- GDay/src/main/java/team/project/gday/review/model/service/ReviewService.java
- GDay/src/main/java/team/project/gday/review/model/service/ReviewServiceImpl.java
- GDay/src/main/resources/mappers/review-mapper.xml
- GDay/src/main/webapp/WEB-INF/views/review/reviewView.jsp
- GDay/src/main/webapp/resources/css/mypage/reviewList.css
> 상세 조회 후기 조회

- GDay/src/main/webapp/WEB-INF/views/gClass/gClassView.jsp
- GDay/src/main/webapp/WEB-INF/views/gift/giftView.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemCancelViewC.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemCancelViewG.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemOrderListJSC.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemOrderListJSG.jsp
- GDay/src/main/webapp/WEB-INF/views/mypage/gMemPage/gMemOrderViewJS.jsp
- GDay/src/main/webapp/resources/css/gClass/gClassView.css
- GDay/src/main/webapp/resources/css/gift/giftView.css
마이페이지 문의하기 버튼 적용 + gClass/giftView 위시리스트 버튼 삭제 + 폰트 적용
> 마이페이지 문의하기 버튼 적용 + gClass/giftView 위시리스트 버튼 삭제 + 폰트 적용

- GDay/src/main/webapp/WEB-INF/views/review/reviewView.jsp
상세 후기 목록 신고 버튼 삭제(기능 구현하려면 시간 걸릴 거 같아서 임시 주석처리)
> 상세 후기 목록 신고 버튼 삭제(기능 구현하려면 시간 걸릴 거 같아서 임시 주석처리)

- GDay/src/main/webapp/WEB-INF/views/calendar/calendarJS.jsp
캘린더 수정 : 등록/수정 후 해당 이벤트 날짜에 머무르게 하기
> 캘린더 수정 : 등록/수정 후 해당 이벤트 날짜에 머무르게 하기

- GDay/src/main/webapp/WEB-INF/views/common/header.jsp
헤더 : 마이캘린더 로그인 후에만 접근 가능하도록 조건 추가
> 헤더 : 마이캘린더 로그인 후에만 접근 가능하도록 조건 추가

- GDay/src/main/webapp/WEB-INF/views/gClass/gClassList.jsp
- GDay/src/main/webapp/WEB-INF/views/gClass/gClassView.jsp
- GDay/src/main/webapp/resources/css/gClass/gClassList.css
gclass 목록, 뷰 css + 가격 표시(천원단위)
> gclass 목록, 뷰 css + 가격 표시(천원단위)

- GDay/src/main/webapp/WEB-INF/views/gClass/gClassList.jsp
- GDay/src/main/webapp/WEB-INF/views/gClass/gClassView.jsp
- GDay/src/main/webapp/WEB-INF/views/gift/giftList.jsp
- GDay/src/main/webapp/WEB-INF/views/gift/giftView.jsp
- GDay/src/main/webapp/WEB-INF/views/magazine/magazine.jsp
- GDay/src/main/webapp/WEB-INF/views/magazine/magazineView.jsp
- GDay/src/main/webapp/resources/css/gClass/gClassList.css
- GDay/src/main/webapp/resources/css/gClass/gClassView.css
- GDay/src/main/webapp/resources/css/gift/gift.css
- GDay/src/main/webapp/resources/css/gift/giftView.css
- GDay/src/main/webapp/resources/css/magazine/magazine.css
- GDay/src/main/webapp/resources/css/magazine/magazineView.css
> 선물찾기, 클래스찾기, 매거진 폰트 적용

- GDay/src/main/java/team/project/gday/admin/controller/AdminController.java
- GDay/src/main/java/team/project/gday/admin/model/dao/AdminDAO.java
- GDay/src/main/java/team/project/gday/admin/model/service/AdminService.java
- GDay/src/main/java/team/project/gday/admin/model/service/AdminServiceImpl.java
- GDay/src/main/resources/mappers/admin-mapper.xml
- GDay/src/main/webapp/WEB-INF/views/admin/adminBMemView.jsp
- GDay/src/main/webapp/WEB-INF/views/admin/adminBlackMem.jsp
- GDay/src/main/webapp/WEB-INF/views/admin/adminBoard.jsp
- GDay/src/main/webapp/WEB-INF/views/admin/adminCustomerService.jsp
- GDay/src/main/webapp/WEB-INF/views/admin/adminMember.jsp
- GDay/src/main/webapp/WEB-INF/views/admin/adminReply.jsp
- GDay/src/main/webapp/WEB-INF/views/admin/adminReportStand.jsp
- GDay/src/main/webapp/WEB-INF/views/admin/reportResult.jsp
> 신고기능 추가(신고 회원/게시물 3회이상 등급 변경)

- GDay/src/main/java/team/project/gday/common/scheduling/CalendarScheduling.java
> 캘린더 스케줄링 주석정리

- GDay/src/main/java/team/project/gday/calendar/model/service/CalendarServiceImpl.java
> 캘린더 문자 자동 알림 로직 수정(버그 수정)
